### ISSUE TITLE
Problem in the menu bar

### ISSUE THREAD

**Issue by sanfm12** [martakostova/pomodoro#23]
Hi,
When the app is launched, its menu bar itens seem to be collapsed. When the timer is started, though, the viewing goes back to normal.
As you can see, I'm using the dark theme.
Thank you
![itens](https://cloud.githubusercontent.com/assets/7762205/5578772/27e1e3e6-9015-11e4-961b-1bf00b5dd57e.png)

**Comment by martakostova** [comment]
The issue is fixed with the new 2.0.4 version. It should be accessible soon at the store

**Comment by sanfm12** [comment]
It's fixed, thank you very much =)
But it still doesn't save names with emoji, after relaunching, everything is gone. 
Can you please fix it?

**Comment by martakostova** [comment]
Yes, will fix it. It is added as another issue, so I close this.
